# Generated by Django 5.0.6 on 2024-07-03 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0002_alter_cliente_apellido_alter_cliente_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='libro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('autor', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='revista',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('editorial', models.CharField(max_length=20)),
                ('titulo', models.CharField(max_length=20)),
                ('telefono', models.IntegerField(max_length=15)),
            ],
        ),
    ]
