# Generated by Django 5.0.6 on 2024-07-04 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0003_libro_revista'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='telefono',
        ),
        migrations.AddField(
            model_name='cliente',
            name='biografia',
            field=models.TextField(default='Sin biografía'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.EmailField(default='example@example.com', max_length=254),
        ),
        migrations.AddField(
            model_name='libro',
            name='apellido_del_dueño',
            field=models.CharField(default='ApellidoFicticio', max_length=20),
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_del_dueño',
            field=models.CharField(default='NombreFicticio', max_length=20),
        ),
        migrations.AddField(
            model_name='libro',
            name='telefono_del_dueño',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AddField(
            model_name='revista',
            name='apellido_del_dueño',
            field=models.CharField(default='ApellidoFicticio', max_length=20),
        ),
        migrations.AddField(
            model_name='revista',
            name='nombre_del_dueño',
            field=models.CharField(default='NombreFicticio', max_length=20),
        ),
        migrations.AddField(
            model_name='revista',
            name='telefono_del_dueño',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='revista',
            name='editorial',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='revista',
            name='titulo',
            field=models.CharField(max_length=100),
        ),
    ]
