# Generated by Django 5.0.6 on 2024-07-04 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0004_remove_libro_telefono_remove_revista_telefono_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libro',
            old_name='apellido_del_dueño',
            new_name='apellido_del_duenio',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='nombre_del_dueño',
            new_name='nombre_del_duenio',
        ),
        migrations.RenameField(
            model_name='libro',
            old_name='telefono_del_dueño',
            new_name='telefono_del_duenio',
        ),
        migrations.RenameField(
            model_name='revista',
            old_name='apellido_del_dueño',
            new_name='apellido_del_duenio',
        ),
        migrations.RenameField(
            model_name='revista',
            old_name='nombre_del_dueño',
            new_name='nombre_del_duenio',
        ),
        migrations.RenameField(
            model_name='revista',
            old_name='telefono_del_dueño',
            new_name='telefono_del_duenio',
        ),
    ]
