# Generated by Django 5.0.6 on 2024-07-04 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0005_rename_apellido_del_dueño_libro_apellido_del_duenio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='libros/'),
        ),
        migrations.AddField(
            model_name='revista',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='revistas/'),
        ),
    ]
