# Generated by Django 5.0.6 on 2024-07-04 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0006_libro_imagen_revista_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='cliente',
        ),
        migrations.AlterField(
            model_name='libro',
            name='apellido_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='telefono_del_duenio',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='revista',
            name='apellido_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='nombre_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='telefono_del_duenio',
            field=models.CharField(max_length=15),
        ),
    ]
