# Generated by Django 5.0.6 on 2024-07-04 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0008_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='seccion',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='texto',
            field=models.TextField(default=''),
        ),
    ]
