# Generated by Django 5.0.6 on 2024-07-04 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0010_alter_comentario_seccion_alter_comentario_texto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='revista',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='libro',
            name='apellido_del_duenio',
            field=models.CharField(default='ApellidoFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_del_duenio',
            field=models.CharField(default='NombreFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='telefono_del_duenio',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='revista',
            name='apellido_del_duenio',
            field=models.CharField(default='ApellidoFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='nombre_del_duenio',
            field=models.CharField(default='NombreFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='telefono_del_duenio',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
