# Generated by Django 5.0.6 on 2024-07-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0013_alter_libro_apellido_del_duenio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='apellido_del_duenio',
            field=models.CharField(default='ApellidoFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_del_duenio',
            field=models.CharField(default='NombreFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='telefono_del_duenio',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
        migrations.AlterField(
            model_name='revista',
            name='apellido_del_duenio',
            field=models.CharField(default='ApellidoFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='nombre_del_duenio',
            field=models.CharField(default='NombreFicticio', max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='telefono_del_duenio',
            field=models.CharField(default='000-000-0000', max_length=15),
        ),
    ]
