# Generated by Django 5.0.6 on 2024-07-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0016_alter_libro_usuario_alter_revista_usuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='revista',
            name='usuario',
        ),
        migrations.AlterField(
            model_name='libro',
            name='apellido_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='nombre_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='libro',
            name='telefono_del_duenio',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='revista',
            name='apellido_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='nombre_del_duenio',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='revista',
            name='telefono_del_duenio',
            field=models.CharField(max_length=15),
        ),
    ]
