# Generated by Django 5.0.6 on 2024-07-04 08:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Appbase', '0017_remove_libro_usuario_remove_revista_usuario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='apellido_del_duenio',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='nombre_del_duenio',
        ),
        migrations.AddField(
            model_name='libro',
            name='usuario',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
